<?php
/**
 * Copyright © Aitoc. All rights reserved.
 */
declare(strict_types=1);
?>
<?php
/** @var $block \Aitoc\MicrosoftClarity\Block\Script */
/** @var $escaper \Magento\Framework\Escaper */
if ($block->isEnabled()):
    $clarityCode = $block->getClarityTrackingCode();
    ?>
    <!-- BEGIN MICROSOFT CLARITY TRACKING CODE -->
    <script type="text/javascript">
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i+"?ref=aitoc";
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            <?php if ($block->isCustomerGroupTagEnabled()): ?>
            c.clarity("set", "customer_group", "<?= $escaper->escapeJs($block->getCustomerGroup()) ?>");
            <?php endif; ?>
        })(window, document, "clarity", "script", "<?= /* @noEscape */ $clarityCode ?>");
    </script>
    <!-- END MICROSOFT CLARITY TRACKING CODE -->
<?php endif; ?>
